#!/usr/bin/env node

const { spawn } = require('child_process');

const npmInstall = spawn('npm', ['install', 'lodash'],{
    cwd: path.join(__dirname, '..') 
});

npmInstall.stdout.on('data', (data) => {
  console.log(`stdout: ${data}`);
});

npmInstall.stderr.on('data', (data) => {
  console.error(`stderr: ${data}`);
});

npmInstall.on('close', (code) => {
  console.log(`child process exited with code ${code}`);
});
