import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/nav";
import { ThemeProvider } from "@/features/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <ThemeProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} bg-white text-slate-900 antialiased dark:bg-slate-900 dark:text-slate-50`}
        >
          <section className="container flex min-h-screen flex-col">
            <Nav />

            {children}
          </section>
        </body>
      </ThemeProvider>
    </html>
  );
}
